FROM ghcr.io/r-wasm/webr:main

WORKDIR /work
COPY . /work/Rducks

WORKDIR /work/Rducks

RUN rm -rf Rducks.Rcheck ..Rcheck README.html inst/rducks_extension/build
RUN R CMD build .
RUN Rscript -e 'if (!requireNamespace("pak", quietly = TRUE)) install.packages("pak", repos = "https://cloud.r-project.org")'
RUN Rscript -e 'pak::pak("r-wasm/rwasm", ask = FALSE)'
RUN Rscript -e 'version <- read.dcf("DESCRIPTION")[1, "Version"]; tarball <- sprintf("./Rducks_%s.tar.gz", version); stopifnot(file.exists(tarball)); print(tarball); rwasm::build(tarball)'

CMD ["Rscript", "-e", "version <- read.dcf('DESCRIPTION')[1, 'Version']; artifact <- sprintf('Rducks_%s.tgz', version); stopifnot(file.exists(artifact)); cat(normalizePath(artifact), '\\n')"]
