## Integration test: use_simd_dispatch() + sh configure
##
## Verifies that the scaffold generated by use_simd_dispatch() is actually
## compilable: runs `sh configure` (the generated configure script) in the
## temp package directory and checks that the expected staged object files
## were produced.
##
## This test requires a C compiler and sh on PATH.  It is placed in a
## separate file so it can be skipped in minimal environments without
## affecting the faster unit tests in test-template.R.

local({
  ## Require sh on PATH (configure is a POSIX shell script).
  sh <- Sys.which("sh")
  if (!nzchar(sh)) {
    exit_file("sh not found on PATH; skipping configure integration test")
  }

  ## Prefer R's own CC (works on Rtools on Windows and any R installation).
  cc <- tryCatch(
    system2(file.path(R.home("bin"), "R"),
            args = c("CMD", "config", "CC"),
            stdout = TRUE, stderr = FALSE),
    error = function(e) character(0)
  )
  cc <- if (length(cc) == 1L && nzchar(cc)) cc else ""

  ## Fall back to cc / gcc on PATH.
  if (!nzchar(cc)) cc <- Sys.which("cc")
  if (!nzchar(cc)) cc <- Sys.which("gcc")
  if (!nzchar(cc)) {
    exit_file("No C compiler found; skipping configure integration test")
  }

  tmpdir <- file.path(tempdir(), "rsd_configure_test")
  unlink(tmpdir, recursive = TRUE)
  dir.create(tmpdir, recursive = TRUE)
  on.exit(unlink(tmpdir, recursive = TRUE), add = TRUE)

  ## Write a minimal DESCRIPTION.
  writeLines(c(
    "Package: testsimd",
    "Version: 0.1.0",
    "Title: Test",
    "Description: Test.",
    "Authors@R: person('A', 'B', role = c('aut', 'cre'), email = 'a@b.com')",
    "License: MIT + file LICENSE"
  ), file.path(tmpdir, "DESCRIPTION"))

  ## Generate the scaffold.
  use_simd_dispatch(path = tmpdir, quiet = TRUE)

  ## The generated configure script must exist and be executable-ish.
  cfg <- file.path(tmpdir, "configure")
  expect_true(file.exists(cfg))

  ## Run sh configure. The configure script uses RSD_PACKAGE_ROOT (or pwd) as
  ## the package root; supply it explicitly so we don't depend on working dir.
  ## Use Sys.setenv/Sys.unsetenv instead of system2's env= argument because
  ## env= splits on spaces and breaks when CC contains flags (e.g. -std=gnu2x).
  old_env <- Sys.getenv(c("RSD_PACKAGE_ROOT", "R_HOME", "CC"), unset = NA)
  Sys.setenv(RSD_PACKAGE_ROOT = tmpdir, R_HOME = R.home(), CC = cc)
  on.exit({
    for (nm in names(old_env)) {
      if (is.na(old_env[[nm]])) Sys.unsetenv(nm) else do.call(Sys.setenv, setNames(list(old_env[[nm]]), nm))
    }
  }, add = TRUE)

  result <- system2(
    "sh", args = file.path(tmpdir, "configure"),
    stdout = TRUE, stderr = TRUE
  )
  rc <- attr(result, "status")
  if (!is.null(rc) && rc != 0L) {
    message("configure output:\n", paste(result, collapse = "\n"))
  }
  expect_true(is.null(rc) || rc == 0L,
              info = paste("sh configure failed with status", rc))

  ## configure must have produced src/config.h and src/Makevars.
  expect_true(file.exists(file.path(tmpdir, "src", "config.h")),
              info = "src/config.h not generated by configure")
  expect_true(file.exists(file.path(tmpdir, "src", "Makevars")),
              info = "src/Makevars not generated by configure")

  ## At least one staged core object must exist in src/rsd-lib/.
  rsd_lib <- list.files(file.path(tmpdir, "src", "rsd-lib"),
                         pattern = "\\.o$", full.names = FALSE)
  expect_true(length(rsd_lib) > 0L,
              info = "no staged objects in src/rsd-lib/")

  ## At least one staged kernel object must exist in src/rsd-kernels/.
  rsd_kernels <- list.files(file.path(tmpdir, "src", "rsd-kernels"),
                             pattern = "\\.o$", full.names = FALSE)
  expect_true(length(rsd_kernels) > 0L,
              info = "no staged objects in src/rsd-kernels/")

  ## Prefix substitution must have been applied: no residual \bsd_ in
  ## the generated C dispatch core.
  dispatch_c <- readLines(
    file.path(tmpdir, "tools", "simdDispatch", "simd_dispatch.c"),
    warn = FALSE
  )
  expect_false(any(grepl("\\bsd_", dispatch_c)),
               info = "residual sd_ prefix found in generated simd_dispatch.c")

  ## .def files must also have been substituted (the critical regression).
  ops_def <- readLines(
    file.path(tmpdir, "tools", "simdDispatch", "kernels", "operations.def"),
    warn = FALSE
  )
  expect_false(any(grepl("\\bSD_OPERATION\\b", ops_def)),
               info = "SD_OPERATION not substituted in generated operations.def")
})
